services:
  - type: web
    name: erp-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.10.0
    autoDeploy: true

  - type: web
    name: erp-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    envVars: []
    autoDeploy: true
    rootDir: frontend
